package local.learning.common.models.expense

enum class ExpenseStubCase {
    NONE,
    SUCCESS,
    VALIDATION_ERROR_BAD_GUID,
    VALIDATION_ERROR_BAD_AMOUNT,
    VALIDATION_ERROR_BAD_CARD_GUID,
    VALIDATION_ERROR_BAD_CATEGORY_GUID,
    VALIDATION_ERROR_BAD_SEARCH_FILTER_AMOUNT_FROM,
    VALIDATION_ERROR_BAD_SEARCH_FILTER_AMOUNT_TO,
    VALIDATION_ERROR_BAD_SEARCH_FILTER_SOURCES,
    VALIDATION_ERROR_BAD_STATISTIC_FILTER_DATE_FROM,
    VALIDATION_ERROR_BAD_STATISTIC_FILTER_DATE_TO,

}