# Swagger UI

version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./../specs/v1/:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml