package local.learning.common.models.card

enum class CardStubCase {
    NONE,
    SUCCESS,
    VALIDATION_ERROR_BAD_GUID,
    VALIDATION_ERROR_BAD_NUMBER,
    VALIDATION_ERROR_BAD_VALID_FOR,
    VALIDATION_ERROR_BAD_OWNER,
    VALIDATION_ERROR_BAD_BANK_GUID

}