openapi: 3.0.3
info:
  title: "Personal Financial Management Service"
  version: 1.0.0
  contact:
    name: Mikhail Sazonov
    email: wursta@gmail.com
servers:
  - url: http://localhost:8080/api
    description: 'Local'
tags:
  - name: Card
    description: Банковская карта
  - name: Expense
    description: Трата
paths:
  /card/create:
    post:
      tags:
        - Card
      summary: Добавление банковской карты
      operationId: cardCreate
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardCreateRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardCreateResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /card/read:
    post:
      tags:
        - Card
      summary: Получение данных банковской карты
      operationId: cardRead
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardReadRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardReadResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /card/update:
    post:
      tags:
        - Card
      summary: Обновление данных банковской карты
      operationId: cardUpdate
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardUpdateRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardUpdateResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /card/delete:
    post:
      tags:
        - Card
      summary: Удаление банковской карты
      operationId: cardDelete
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardDeleteRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardDeleteResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'

  /expense/create:
    post:
      tags:
        - Expense
      summary: Добавление траты
      operationId: expenseCreate
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseCreateRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCreateResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /expense/read:
    post:
      tags:
        - Expense
      summary: Получение данных траты
      operationId: expenseRead
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseReadRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseReadResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /expense/update:
    post:
      tags:
        - Expense
      summary: Обновление данных траты
      operationId: expenseUpdate
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseUpdateRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseUpdateResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /expense/delete:
    post:
      tags:
        - Expense
      summary: Удаление траты
      operationId: expenseDelete
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseDeleteRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseDeleteResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /expense/search:
    post:
      tags:
        - Expense
      summary: Поиск трат по фильтрам
      operationId: expenseSearch
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseSearchRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseSearchResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /expense/stats:
    post:
      tags:
        - Expense
      summary: Поиск статистики по тратам
      operationId: expenseStats
      security:
        - basicAuth: [ ]
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseStatsRequest'
        required: true
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseStatsResponse'
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    # COMMON
    IRequest:
      type: object
      description: Мета-данные для всех запросов
      properties:
        requestType:
          type: string
          description: Поле с информацией о типе запроса
          example: create
        requestId:
          type: string
          description: Идентификатор запроса для отладки
      discriminator:
        propertyName: requestType
        mapping:
          cardCreate: '#/components/schemas/CardCreateRequest'
          cardRead: '#/components/schemas/CardReadRequest'
          cardUpdate: '#/components/schemas/CardUpdateRequest'
          cardDelete: '#/components/schemas/CardDeleteRequest'
          expenseCreate: '#/components/schemas/ExpenseCreateRequest'
          expenseRead: '#/components/schemas/ExpenseReadRequest'
          expenseUpdate: '#/components/schemas/ExpenseUpdateRequest'
          expenseDelete: '#/components/schemas/ExpenseDeleteRequest'
          expensesSearch: '#/components/schemas/ExpenseSearchRequest'
          expensesStats: '#/components/schemas/ExpenseStatsRequest'

    IResponse:
      type: object
      description: Мета-данные для всех ответов
      properties:
        responseType:
          type: string
          description: Поле с информацией о типе ответа
          example: create
        requestId:
          type: string
          description: Идентификатор запроса для отладки
        result:
          $ref: './schemas/ResponseResult.yaml#/ResponseResult'
        errors:
          type: array
          items:
            $ref: './schemas/ResponseError.yaml#/ResponseError'
      discriminator:
        propertyName: requestType
        mapping:
          cardCreate: '#/components/schemas/CardCreateResponse'
          cardRead: '#/components/schemas/CardReadResponse'
          cardUpdate: '#/components/schemas/CardUpdateResponse'
          cardDelete: '#/components/schemas/CardDeleteResponse'
          expenseCreate: '#/components/schemas/ExpenseCreateResponse'
          expenseRead: '#/components/schemas/ExpenseReadResponse'
          expenseUpdate: '#/components/schemas/ExpenseUpdateResponse'
          expenseDelete: '#/components/schemas/ExpenseDeleteResponse'
          expensesSearch: '#/components/schemas/ExpenseSearchResponse'
          expensesStats: '#/components/schemas/ExpenseStatsResponse'

    InternalErrorResponse:
      type: object
      description: Объект описывает свойства для внутренней ошибки сервера
      properties:
        message:
          type: string

    # STUBS
    CardRequestWorkMode:
      type: object
      properties:
        mode:
          type: string
          enum:
            - prod
            - test
            - stub
        stubCase:
          type: string
          description: Возможные стабы
          enum:
            - success
            - bad_guid
            - bad_number
            - bad_valid_for
            - bad_owner
            - bad_bank_guid
            -
    ExpenseRequestWorkMode:
      type: object
      properties:
        mode:
          type: string
          enum:
            - prod
            - test
            - stub
        stubCase:
          type: string
          description: Возможные стабы
          enum:
            - success
            - bad_guid
            - bad_amount
            - bad_card_guid
            - bad_category_guid
            - bad_search_filter_amount_from
            - bad_search_filter_amount_to
            - bad_search_filter_sources
            - bad_statistic_filter_date_from
            - bad_statistic_filter_date_to

    # LOGS
    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    CommonCardLogModel:
      title: Общая модель лога
      description: Общая модель лога для банковских карт
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        card:
          $ref: '#/components/schemas/CardLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    CardLogModel:
      title: Модель лога для банковской карты
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - cardCreate
            - cardRead
            - cardUpdate
            - cardDelete
        requestCard:
          $ref: './schemas/Card.yaml#/CardObject'
        responseCard:
          $ref: './schemas/Card.yaml#/CardObject'

    # REQUESTS & RESPONSES
    # CardCreate
    CardCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/CardRequestWorkMode'
            card:
              $ref: './schemas/Card.yaml#/CardCreateObject'

    CardCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Card.yaml#/CardResponseSingle'

    # CardRead
    CardReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/CardRequestWorkMode'
            guid:
              $ref: './schemas/Card.yaml#/CardGUID'

    CardReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Card.yaml#/CardResponseSingle'

    # CardUpdate
    CardUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/CardRequestWorkMode'
            card:
              $ref: './schemas/Card.yaml#/CardObject'

    CardUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Card.yaml#/CardResponseSingle'

    # CardDelete
    CardDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/CardRequestWorkMode'
            guid:
              $ref: './schemas/Card.yaml#/CardGUID'
            lock:
              $ref: './schemas/Card.yaml#/CardLockGUID'

    CardDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Card.yaml#/CardResponseSingle'

    # ExpenseCreate
    ExpenseCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/ExpenseRequestWorkMode'
            expense:
              $ref: './schemas/Expense.yaml#/ExpenseCreateObject'

    ExpenseCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Expense.yaml#/ExpenseResponseSingle'

    # ExpenseRead
    ExpenseReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/ExpenseRequestWorkMode'
            guid:
              $ref: './schemas/Expense.yaml#/ExpenseGUID'

    ExpenseReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Expense.yaml#/ExpenseResponseSingle'

    # ExpenseUpdate
    ExpenseUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/ExpenseRequestWorkMode'
            expense:
              $ref: './schemas/Expense.yaml#/ExpenseObject'

    ExpenseUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Expense.yaml#/ExpenseResponseSingle'

    # ExpenseDelete
    ExpenseDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/ExpenseRequestWorkMode'
            guid:
              $ref: './schemas/Expense.yaml#/ExpenseGUID'
            lock:
              $ref: './schemas/Expense.yaml#/ExpenseLockGUID'

    ExpenseDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Expense.yaml#/ExpenseResponseSingle'

    # ExpenseSearch
    ExpenseSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: './schemas/Expense.yaml#/ExpenseFilter'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/ExpenseRequestWorkMode'

    ExpenseSearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Expense.yaml#/ExpenseResponseMulti'

    # ExpenseStats
    ExpenseStatsRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: './schemas/Expense.yaml#/ExpenseStatFilter'
        - type: object
          properties:
            workMode:
              $ref: '#/components/schemas/ExpenseRequestWorkMode'

    ExpenseStatsResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: './schemas/Expense.yaml#/ExpenseStat'